# Docker needs superuser permissions
sudo: required

# Added per React Create App errata stuff
language: generic 

# Get Docker ready
services:
  - docker

before_install:
# Use a tag here since we won't easily get the ID back
# Tag only used in this Travis process so could use anything.
  - docker build -t rpetty2012/docker-react -f Dockerfile.dev .

script:
# How to run the test suite.
# Any code not zero means broken
# Travis assumes it ran, or errored.
# NPM run test never exists on its own so it will wait until you give a result
# adding "-- --coverage" changes the default command to generate the correct
# output once it runs the tests (which is automatically on startup)
#
# -e CI=true added due to React Create App issues.
  - docker run -e CI=true rpetty2012/docker-react npm run test -- --coverage

deploy:
  # Travis CI has support for some default providers
  provider: elasticbeanstalk
  # Region EBS defaulted to, found via default app URL.
  region: "us-east-2"
  # EBS target app name
  app: "docker-react"
  # Environment target name, created by EBS
  env: "Dockerreact-dev"
  # Travis CI zips all files into one, copies to 
  # Travis CI then tells EBS to redeploy that zip
  bucket_name: "elasticbeanstalk-us-east-2-353084998536"
  # Defaults to app name until you do your first build which actually uses s3.
  bucket_path: "docker-react"
  # Only publish when merging to master
  on:
    branch: master 
    # DO NOT PUT KEYS IN HERE, USEE SECRETS MANAGEMENT
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"