version: '3'
services:
  # web is just the name for building out the frontend application, could be anything, like react-app or react-web-app, etc
  web:
    build: 
      # where to get the files from
      context: .
      # have to definte this as its not the default name
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]